"""added_invitations_table

Revision ID: 315fc98d0019
Revises: 98c3626941e9
Create Date: 2025-05-28 20:50:01.539124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "315fc98d0019"
down_revision: Union[str, None] = "98c3626941e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invited_at", sa.DateTime(), nullable=False),
        sa.Column("expiration_date", sa.DateTime(), nullable=False),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column("is_accepted", sa.Boolean(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invitations_email"), "invitations", ["email"], unique=False
    )
    op.create_index(op.f("ix_invitations_id"), "invitations", ["id"], unique=False)
    op.create_index(op.f("ix_invitations_token"), "invitations", ["token"], unique=True)
    op.drop_index(op.f("ix_team_mates_email"), table_name="team_mates")
    op.drop_index(op.f("ix_team_mates_invite_token"), table_name="team_mates")
    op.drop_column("team_mates", "email")
    op.drop_column("team_mates", "invite_token")
    op.drop_column("team_mates", "invited_at")
    op.drop_column("team_mates", "cancelled")
    op.drop_column("team_mates", "joined")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team_mates", sa.Column("joined", sa.BOOLEAN(), nullable=False))
    op.add_column("team_mates", sa.Column("cancelled", sa.BOOLEAN(), nullable=False))
    op.add_column("team_mates", sa.Column("invited_at", sa.DATETIME(), nullable=False))
    op.add_column("team_mates", sa.Column("invite_token", sa.VARCHAR(), nullable=False))
    op.add_column("team_mates", sa.Column("email", sa.VARCHAR(), nullable=False))
    op.create_index(
        op.f("ix_team_mates_invite_token"), "team_mates", ["invite_token"], unique=1
    )
    op.create_index(op.f("ix_team_mates_email"), "team_mates", ["email"], unique=False)
    op.drop_index(op.f("ix_invitations_token"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_email"), table_name="invitations")
    op.drop_table("invitations")
    # ### end Alembic commands ###
