"""Add_case-insensitive_unique_constraint_to_team_names

Revision ID: 506e106cdb5e
Revises: b66e6e90c25c
Create Date: 2025-06-19 04:56:03.365325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506e106cdb5e'
down_revision: Union[str, None] = 'b66e6e90c25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_owner_team_name_insensitive', 'teams', ['owner_id', sa.literal_column('lower(name)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_owner_team_name_insensitive', table_name='teams')
    # ### end Alembic commands ###
