"""alter_teams_tables

Revision ID: 72bfacfd767a
Revises: cefbef908268
Create Date: 2025-06-19 02:40:54.406742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72bfacfd767a'
down_revision: Union[str, None] = 'cefbef908268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the enum type
    op.execute("CREATE TYPE teammaterole AS ENUM('owner', 'admin', 'viewer')")

    op.add_column('invitations', sa.Column('invited_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_invitations_invited_by'), 'invitations', ['invited_by'], unique=False)
    op.drop_constraint(op.f('invitations_user_id_fkey'), 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'users', ['invited_by'], ['id'])
    op.drop_column('invitations', 'user_id')

    # Use the created enum type
    op.add_column('team_mates', sa.Column('role', sa.Enum('owner', 'admin', 'viewer', name='teammaterole'), nullable=False))
    op.create_index(op.f('ix_team_mates_role'), 'team_mates', ['role'], unique=False)
    op.alter_column('teams', 'code',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.create_index(op.f('ix_teams_code'), 'teams', ['code'], unique=False)
    op.create_index(op.f('ix_teams_owner_id'), 'teams', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_owner_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_code'), table_name='teams')
    op.alter_column('teams', 'code',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_index(op.f('ix_team_mates_role'), table_name='team_mates')
    op.drop_column('team_mates', 'role')
    op.add_column('invitations', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key(op.f('invitations_user_id_fkey'), 'invitations', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_invitations_invited_by'), table_name='invitations')
    op.drop_column('invitations', 'invited_by')

    # Drop the enum type in downgrade (important for reversibility)
    op.execute("DROP TYPE teammaterole")
    # ### end Alembic commands ###