"""add_role_field_to_invitations_model

Revision ID: 9514dd2bcfac
Revises: 506e106cdb5e
Create Date: 2025-06-21 06:05:21.670161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9514dd2bcfac'
down_revision: Union[str, None] = '506e106cdb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'VIEWER', name='teammaterole'), nullable=False))
    op.create_index(op.f('ix_invitations_role'), 'invitations', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitations_role'), table_name='invitations')
    op.drop_column('invitations', 'role')
    # ### end Alembic commands ###
